version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Package Artifact"
      #- echo Code Scanning using SonarQube
      #- mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=mahendrakanna1_devb78am
      #- mvn verify sonar:sonar
      #- echo Connecting AWS CodeArtifact 
      #- export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain b78am --domain-owner 471112668453 --region us-east-1 --query authorizationToken --output text`      
  build:
    commands:
      - echo Build started on `date`
      - pwd
      - ls -lrta
      - ls -lrt $CODEBUILD_SRC_DIR/settings.xml
      - cp -pvr $CODEBUILD_SRC_DIR/settings.xml ~/.m2/settings.xml
      - mvn deploy
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/devtools.war
